import { mockSliceAt } from "@/lib/mock-slices";
import type {
  AccrualVarianceBucket,
  ActivityItem,
  ApprovalQueueItem,
  AuditTrailEntry,
  BreakdownLine,
  BrokerPerformanceRow,
  ChannelEarningRow,
  CommissionRuleSet,
  DashboardAlert,
  DataQualityIssue,
  IncentivePayoutCurvePoint,
  Integration,
  IntegrationLogEntry,
  KpiSummary,
  LeaderboardRow,
  MisReportRow,
  MisTrendPoint,
  MonthlyPerformancePoint,
  NotificationAlertRule,
  NotificationCampaignDraft,
  PerformanceSignalRow,
  ProductCommissionRow,
  ReportJob,
  RuleEngineRule,
  RuleVersionMeta,
  ScheduledReportJob,
  TargetRow,
  TopExposureRow,
  TrendPoint,
  User,
} from "./types";

export const mockUser: User = {
  id: "u-1",
  name: "Sara Al-Mansoori",
  email: "sara.almansoori@example.com",
  role: "manager",
  team: "Commercial Lines — Muscat",
};

export const mockKpis: KpiSummary[] = [
  {
    id: "k1",
    label: "Total Incentive",
    value: "OMR 42,180",
    change: "+12.4% vs last quarter",
    trend: "up",
  },
  {
    id: "k2",
    label: "Achievement %",
    value: "85%",
    change: "Quarter-to-date · Tier 2 band",
    trend: "up",
  },
  {
    id: "k3",
    label: "Pending payout",
    value: "OMR 8,400",
    change: "Next settlement 15 Apr · YTD paid OMR 33,780",
    trend: "neutral",
  },
  {
    id: "k4",
    label: "Risk indicator",
    value: "Elevated",
    change: "2 open breaches · motor renewals under review",
    trend: "down",
  },
];

export const mockTrend: TrendPoint[] = [
  {
    period: "Jul",
    revenue: 265000,
    incentive: 10600,
    slice: mockSliceAt(0),
  },
  {
    period: "Aug",
    revenue: 272000,
    incentive: 10950,
    slice: mockSliceAt(1),
  },
  {
    period: "Sep",
    revenue: 288000,
    incentive: 11520,
    slice: mockSliceAt(2),
  },
  {
    period: "Oct",
    revenue: 295000,
    incentive: 11880,
    slice: mockSliceAt(3),
  },
  {
    period: "Nov",
    revenue: 302000,
    incentive: 12100,
    slice: mockSliceAt(4),
  },
  {
    period: "Dec",
    revenue: 318000,
    incentive: 12720,
    slice: mockSliceAt(5),
  },
  {
    period: "Jan",
    revenue: 280000,
    incentive: 11200,
    slice: mockSliceAt(6),
  },
  {
    period: "Feb",
    revenue: 310000,
    incentive: 12800,
    slice: mockSliceAt(7),
  },
  {
    period: "Mar",
    revenue: 355000,
    incentive: 14600,
    slice: mockSliceAt(0),
  },
  {
    period: "Apr",
    revenue: 298000,
    incentive: 12100,
    slice: mockSliceAt(1),
  },
  {
    period: "May",
    revenue: 332000,
    incentive: 13500,
    slice: mockSliceAt(2),
  },
  {
    period: "Jun",
    revenue: 368000,
    incentive: 15180,
    slice: mockSliceAt(3),
  },
];

/** Monthly achievement + incentive for MoM / YoY dashboard */
export const mockMonthlyPerformance: MonthlyPerformancePoint[] = [
  {
    month: "Jan",
    achievementPct: 72,
    incentiveK: 11.2,
    incentivePriorYearK: 9.8,
    slice: mockSliceAt(0),
  },
  {
    month: "Feb",
    achievementPct: 76,
    incentiveK: 12.8,
    incentivePriorYearK: 10.5,
    slice: mockSliceAt(1),
  },
  {
    month: "Mar",
    achievementPct: 81,
    incentiveK: 14.6,
    incentivePriorYearK: 11.9,
    slice: mockSliceAt(2),
  },
  {
    month: "Apr",
    achievementPct: 78,
    incentiveK: 12.1,
    incentivePriorYearK: 11.2,
    slice: mockSliceAt(3),
  },
  {
    month: "May",
    achievementPct: 83,
    incentiveK: 13.5,
    incentivePriorYearK: 12.0,
    slice: mockSliceAt(4),
  },
  {
    month: "Jun",
    achievementPct: 85,
    incentiveK: 15.18,
    incentivePriorYearK: 12.7,
    slice: mockSliceAt(5),
  },
];

export const mockActivities: ActivityItem[] = [
  {
    id: "a1",
    title: "Deal closed — Marine hull",
    description: "OMR 185,000 premium · Incentive accrual updated",
    time: "2h ago",
    type: "deal",
  },
  {
    id: "a2",
    title: "March payout released",
    description: "OMR 14,200 credited to wallet",
    time: "Yesterday",
    type: "payout",
  },
  {
    id: "a3",
    title: "KPI threshold reminder",
    description: "Motor renewals within 8% of accelerator band",
    time: "2d ago",
    type: "alert",
  },
  {
    id: "a4",
    title: "Target allocation updated",
    description: "Q2 goals published for Commercial — Muscat",
    time: "3d ago",
    type: "alert",
  },
  {
    id: "a5",
    title: "Deal closed — Fleet motor",
    description: "OMR 92,400 premium · NB multiplier applied",
    time: "4d ago",
    type: "deal",
  },
];

export const mockLeaderboard: LeaderboardRow[] = [
  {
    id: "lb-1",
    rank: 1,
    name: "Yousuf Al-Balushi",
    team: "Retail — Salalah",
    revenue: 512000,
    incentive: 52800,
    kpiScore: 94,
    delta: 1,
    slice: mockSliceAt(0),
  },
  {
    id: "lb-2",
    rank: 2,
    name: "Sara Al-Mansoori",
    team: "Commercial — Muscat",
    revenue: 488000,
    incentive: 49200,
    kpiScore: 91,
    delta: -1,
    slice: mockSliceAt(1),
  },
  {
    id: "lb-3",
    rank: 3,
    name: "Hamed Al-Saadi",
    team: "Corporate — Muscat",
    revenue: 465000,
    incentive: 46100,
    kpiScore: 88,
    delta: 0,
    slice: mockSliceAt(2),
  },
  {
    id: "lb-4",
    rank: 4,
    name: "Fatima Al-Rashidi",
    team: "Retail — Sohar",
    revenue: 421000,
    incentive: 40200,
    kpiScore: 84,
    delta: 2,
    slice: mockSliceAt(3),
  },
  {
    id: "lb-5",
    rank: 5,
    name: "Khalid Al-Harthy",
    team: "SME — Muscat",
    revenue: 398000,
    incentive: 38100,
    kpiScore: 81,
    delta: -1,
    slice: mockSliceAt(4),
  },
];

export const mockBreakdown: BreakdownLine[] = [
  {
    id: "b1",
    component: "Base incentive (Tier 2 slab)",
    amount: 28400,
    dealRef: "Plan FY25 — Commercial",
    period: "Q1 2026",
    slice: mockSliceAt(0),
  },
  {
    id: "b2",
    component: "Variable — new business multiplier",
    amount: 9200,
    dealRef: "NB x1.15",
    period: "Q1 2026",
    slice: mockSliceAt(1),
  },
  {
    id: "b3",
    component: "Accelerator — overachievement",
    amount: 4580,
    dealRef: "Motor renewals > 92%",
    period: "Q1 2026",
    slice: mockSliceAt(2),
  },
];

export const mockReports: ReportJob[] = [
  {
    id: "r1",
    name: "Executive incentive summary",
    format: "pdf",
    lastRun: "2026-04-01",
    status: "ready",
    slice: mockSliceAt(0),
  },
  {
    id: "r2",
    name: "Deal-level breakdown",
    format: "xlsx",
    lastRun: "2026-03-28",
    status: "scheduled",
    slice: mockSliceAt(1),
  },
  {
    id: "r3",
    name: "Leaderboard export",
    format: "csv",
    lastRun: "2026-03-15",
    status: "failed",
    slice: mockSliceAt(2),
  },
];

export const mockTargets: TargetRow[] = [
  {
    id: "t1",
    metric: "Gross written premium",
    target: 1200000,
    achieved: 1020000,
    unit: "OMR",
    owner: "Commercial — Muscat",
  },
  {
    id: "t2",
    metric: "New policies (count)",
    target: 180,
    achieved: 156,
    unit: "count",
    owner: "Sara Al-Mansoori",
  },
  {
    id: "t3",
    metric: "Renewal retention",
    target: 92,
    achieved: 88.4,
    unit: "%",
    owner: "Team Retail",
  },
];

export const mockIntegrations: Integration[] = [
  {
    id: "i1",
    name: "Salesforce CRM",
    provider: "Salesforce",
    status: "connected",
    lastSync: "12 min ago",
  },
  {
    id: "i2",
    name: "HubSpot pipeline",
    provider: "HubSpot",
    status: "disconnected",
  },
  {
    id: "i3",
    name: "Finance ledger",
    provider: "Internal",
    status: "error",
    lastSync: "3h ago",
  },
];

/** Recognition buckets: variance = earned − expected (accrual). Chart cumulates Σ variance. */
export const mockAccrualVarianceBuckets: AccrualVarianceBucket[] = [
  {
    bucket: "W1",
    earnedK: 9.2,
    expectedK: 10.5,
    varianceK: -1.3,
    slice: mockSliceAt(0),
  },
  {
    bucket: "W2",
    earnedK: 11.0,
    expectedK: 10.8,
    varianceK: 0.2,
    slice: mockSliceAt(1),
  },
  {
    bucket: "W3",
    earnedK: 10.4,
    expectedK: 11.2,
    varianceK: -0.8,
    slice: mockSliceAt(2),
  },
  {
    bucket: "W4",
    earnedK: 12.6,
    expectedK: 11.0,
    varianceK: 1.6,
    slice: mockSliceAt(3),
  },
  {
    bucket: "W5",
    earnedK: 11.8,
    expectedK: 12.4,
    varianceK: -0.6,
    slice: mockSliceAt(4),
  },
  {
    bucket: "W6",
    earnedK: 13.1,
    expectedK: 12.0,
    varianceK: 1.1,
    slice: mockSliceAt(5),
  },
  {
    bucket: "W7",
    earnedK: 12.0,
    expectedK: 12.8,
    varianceK: -0.8,
    slice: mockSliceAt(6),
  },
  {
    bucket: "W8",
    earnedK: 14.2,
    expectedK: 12.5,
    varianceK: 1.7,
    slice: mockSliceAt(7),
  },
  {
    bucket: "W9",
    earnedK: 13.5,
    expectedK: 13.2,
    varianceK: 0.3,
    slice: mockSliceAt(0),
  },
  {
    bucket: "W10",
    earnedK: 14.0,
    expectedK: 13.8,
    varianceK: 0.2,
    slice: mockSliceAt(1),
  },
];

/**
 * Achievement % (X) vs payout: below 80% no earn; 80–100% target band; >100% accelerator.
 * Multiplier is effective vs base tier-1 earn rate at 100% achievement.
 */
export const mockIncentivePayoutCurve: IncentivePayoutCurvePoint[] = [
  {
    label: "W2",
    revenueK: 186,
    achievementPct: 64,
    incentiveEarnedK: 0,
    payoutMultiplier: 0,
    appliedSlab: "Below threshold (<80%)",
    slice: mockSliceAt(0),
  },
  {
    label: "W4",
    revenueK: 205,
    achievementPct: 72,
    incentiveEarnedK: 0,
    payoutMultiplier: 0,
    appliedSlab: "Below threshold (<80%)",
    slice: mockSliceAt(1),
  },
  {
    label: "W6",
    revenueK: 228,
    achievementPct: 79,
    incentiveEarnedK: 0.9,
    payoutMultiplier: 0.12,
    appliedSlab: "Threshold approach (ramp)",
    slice: mockSliceAt(2),
  },
  {
    label: "W7",
    revenueK: 236,
    achievementPct: 82,
    incentiveEarnedK: 6.2,
    payoutMultiplier: 0.72,
    appliedSlab: "Target band (80–100%)",
    slice: mockSliceAt(3),
  },
  {
    label: "W8",
    revenueK: 248,
    achievementPct: 88,
    incentiveEarnedK: 12.4,
    payoutMultiplier: 1.0,
    appliedSlab: "Target band (80–100%)",
    slice: mockSliceAt(4),
  },
  {
    label: "W9",
    revenueK: 258,
    achievementPct: 94,
    incentiveEarnedK: 17.8,
    payoutMultiplier: 1.12,
    appliedSlab: "Target band (80–100%)",
    slice: mockSliceAt(5),
  },
  {
    label: "W10",
    revenueK: 268,
    achievementPct: 99,
    incentiveEarnedK: 22.6,
    payoutMultiplier: 1.22,
    appliedSlab: "Target band (80–100%)",
    slice: mockSliceAt(6),
  },
  {
    label: "W11",
    revenueK: 276,
    achievementPct: 103,
    incentiveEarnedK: 31.4,
    payoutMultiplier: 1.35,
    appliedSlab: "Accelerator (>100%)",
    slice: mockSliceAt(7),
  },
  {
    label: "W12",
    revenueK: 284,
    achievementPct: 108,
    incentiveEarnedK: 38.2,
    payoutMultiplier: 1.42,
    appliedSlab: "Accelerator (>100%)",
    slice: mockSliceAt(0),
  },
];

export const mockDashboardAlerts: DashboardAlert[] = [
  {
    id: "da-1",
    severity: "critical",
    title: "Accelerator band at risk",
    metric: "Motor renewals −8% vs run-rate",
    detail: "Commercial — Muscat · Review before 12 Apr cutoff",
    slice: mockSliceAt(0),
  },
  {
    id: "da-2",
    severity: "warning",
    title: "Payout reconciliation lag",
    metric: "OMR 8.4k pending sign-off",
    detail: "Finance queue · SLA 48h",
    slice: mockSliceAt(1),
  },
  {
    id: "da-3",
    severity: "warning",
    title: "Target drift",
    metric: "Q2 GWP trail −3.2%",
    detail: "Rolling 8-week forecast",
    slice: mockSliceAt(2),
  },
  {
    id: "da-4",
    severity: "info",
    title: "Plans within tolerance",
    metric: "94% of LOBs on track",
    detail: "Last full refresh · mock data",
    slice: mockSliceAt(3),
  },
];

export const mockTopExposures: TopExposureRow[] = [
  {
    id: "ex-1",
    exposure: "Fleet motor — Oman Cement",
    segment: "Commercial",
    riskRating: "A−",
    maturity: "Aug 2027",
    amountOmr: 420000,
    sharePct: 18.4,
    slice: mockSliceAt(0),
  },
  {
    id: "ex-2",
    exposure: "Marine hull — Port Salalah",
    segment: "Marine",
    riskRating: "BBB+",
    maturity: "Jan 2026",
    amountOmr: 298000,
    sharePct: 12.1,
    slice: mockSliceAt(1),
  },
  {
    id: "ex-3",
    exposure: "Property — Muscat Mall",
    segment: "Property",
    riskRating: "A",
    maturity: "Mar 2028",
    amountOmr: 256000,
    sharePct: 9.8,
    slice: mockSliceAt(2),
  },
  {
    id: "ex-4",
    exposure: "Medical group — Govt scheme",
    segment: "Health",
    riskRating: "AA−",
    maturity: "Dec 2026",
    amountOmr: 198000,
    sharePct: 8.2,
    slice: mockSliceAt(3),
  },
  {
    id: "ex-5",
    exposure: "Motor retail book (top decile)",
    segment: "Retail",
    riskRating: "B+",
    maturity: "Rolling",
    amountOmr: 142000,
    sharePct: 6.5,
    slice: mockSliceAt(4),
  },
  {
    id: "ex-6",
    exposure: "Engineering — PDO bundle",
    segment: "Engineering",
    riskRating: "A",
    maturity: "Jun 2027",
    amountOmr: 118000,
    sharePct: 5.1,
    slice: mockSliceAt(5),
  },
];

export const mockApprovalQueue: ApprovalQueueItem[] = [
  {
    id: "ap-1",
    title: "Q2 Executive Accelerator Batch — Corporate Muscat",
    detail: "High-value incentive true-up (14 producers) following March performance sweep. Requires business validation of Tier-3 overrides.",
    amountOmr: 18420,
    submitter: "Ahmed Al-Rashid",
    submittedAt: "2026-04-08T09:12:00",
    status: "pending",
    currentStage: "sales",
    stages: [
      {
        stage: "ops",
        label: "Operations",
        status: "complete",
        actor: "Hilal Al-Mahrouqi",
        actedAt: "2026-04-08T10:05:00",
        comment: "Systems check: Premium data integrity verified against core policy engine. All 14 lines within slab tolerance.",
      },
      {
        stage: "sales",
        label: "Sales",
        status: "pending",
      },
      { stage: "finance", label: "Finance", status: "pending" },
      { stage: "payout", label: "Payout", status: "pending" },
    ],
  },
  {
    id: "ap-2",
    title: "Motor Retail SPIFF — Eid Promotion Phase 1",
    detail: "Promotional payout for MRT-03 campaign (38 policies). Includes manual adjustments for referral bonuses.",
    amountOmr: 4920,
    submitter: "Layla Al-Balushi",
    submittedAt: "2026-04-07T14:40:00",
    status: "pending",
    currentStage: "ops",
    stages: [
      { stage: "ops", label: "Operations", status: "pending" },
      { stage: "sales", label: "Sales", status: "pending" },
      { stage: "finance", label: "Finance", status: "pending" },
      { stage: "payout", label: "Payout", status: "pending" },
    ],
  },
  {
    id: "ap-3",
    title: "Deep-Sea Marine Hull Override — Port Deal 2026",
    detail: "Complex risk exception authorized by UW committee on 02-Apr. Manual override of base commission rates.",
    amountOmr: 6200,
    submitter: "Omar Al-Siyabi",
    submittedAt: "2026-04-05T11:00:00",
    status: "approved",
    currentStage: "payout",
    stages: [
      {
        stage: "ops",
        label: "Operations",
        status: "complete",
        actor: "Hilal Al-Mahrouqi",
        actedAt: "2026-04-05T15:20:00",
        comment: "Approved logic: Exception code ME-42 applied for non-standard marine vessel coverage.",
      },
      {
        stage: "sales",
        label: "Sales",
        status: "complete",
        actor: "Sara Al-Mansoori",
        actedAt: "2026-04-06T09:00:00",
        comment: "Strategic account sign-off confirmed by MD. Premium receipt verified.",
      },
      {
        stage: "finance",
        label: "Finance",
        status: "complete",
        actor: "Finance Ops",
        actedAt: "2026-04-07T08:30:00",
        comment: "Accrual provisioned in G/L. Tax withholdings calculated.",
      },
      {
        stage: "payout",
        label: "Payout",
        status: "complete",
        actor: "Payroll",
        actedAt: "2026-04-07T16:00:00",
        comment: "Transaction ID #77241. Funds cleared to producer wallet.",
      },
    ],
  },
  {
    id: "ap-4",
    title: "National Health Group Renewal Incentive",
    detail: "Rejected due to mismatch in eligibility duration. File failed Phase 1 automated validation.",
    amountOmr: 11200,
    submitter: "Noor Al-Hinai",
    submittedAt: "2026-04-02T16:00:00",
    status: "rejected",
    currentStage: "ops",
    stages: [
      {
        stage: "ops",
        label: "Operations",
        status: "rejected",
        actor: "Hilal Al-Mahrouqi",
        actedAt: "2026-04-03T10:15:00",
        comment: "Critical error: Missing broker attestation for the 24-month renewal clause. Refer to Policy B-14.",
      },
      { stage: "sales", label: "Sales", status: "pending" },
      { stage: "finance", label: "Finance", status: "pending" },
      { stage: "payout", label: "Payout", status: "pending" },
    ],
  },
];

const defaultSlabs: CommissionRuleSet["slabs"] = [
  {
    id: "s1",
    minAchievementPct: 0,
    maxAchievementPct: 79,
    commissionPct: 4.5,
    payoutMultiplier: 0.35,
  },
  {
    id: "s2",
    minAchievementPct: 80,
    maxAchievementPct: 100,
    commissionPct: 7.2,
    payoutMultiplier: 1.0,
  },
  {
    id: "s3",
    minAchievementPct: 101,
    maxAchievementPct: 130,
    commissionPct: 9.0,
    payoutMultiplier: 1.35,
  },
];

export const mockCommissionRules: CommissionRuleSet[] = [
  {
    id: "cr-1",
    name: "Commercial lines — core slab",
    product: "Motor Fleet - Comprehensive",
    region: "Muscat & Batinah",
    channel: "agent",
    roleScope: "Producer, RM",
    version: "2026.1",
    status: "active",
    effectiveFrom: "2026-01-01",
    updatedAt: "2026-03-18T11:00:00",
    updatedBy: "Policy Admin",
    slabs: defaultSlabs.map((s) => ({ ...s, id: `${s.id}-a` })),
    conditions: {
      excludeChannels: ["staff"],
      allowedRegions: ["Muscat", "Dhofar"],
      allowedStaffIds: ["ST-001", "ST-002"],
    },
  },
  {
    id: "cr-2",
    name: "Retail motor — retail SPIFF stack",
    product: "Retail Motor - Comprehensive",
    region: "National",
    channel: "broker",
    roleScope: "Producer",
    version: "2025.4",
    status: "active",
    effectiveFrom: "2025-10-01",
    updatedAt: "2026-02-02T09:30:00",
    updatedBy: "Sara Al-Mansoori",
    slabs: [
      {
        id: "m1",
        minAchievementPct: 0,
        maxAchievementPct: 85,
        commissionPct: 3.8,
        payoutMultiplier: 0.5,
      },
      {
        id: "m2",
        minAchievementPct: 86,
        maxAchievementPct: 115,
        commissionPct: 6.0,
        payoutMultiplier: 1.0,
      },
    ],
    conditions: {
      excludeChannels: [],
      allowedRegions: ["National"],
      allowedStaffIds: [],
    },
  },
  {
    id: "cr-3",
    name: "Marine & cargo — draft Q3",
    product: "Motor Fleet - TP",
    region: "Salalah, Sohar",
    channel: "staff",
    roleScope: "Producer",
    version: "2026.2-draft",
    status: "draft",
    effectiveFrom: "2026-07-01",
    updatedAt: "2026-04-01T14:00:00",
    updatedBy: "Actuarial",
    slabs: defaultSlabs.map((s) => ({ ...s, id: `${s.id}-d` })),
    conditions: {
      excludeChannels: ["broker"],
      allowedRegions: ["Salalah", "Sohar"],
      allowedStaffIds: ["ST-003"],
    },
  },
];

export const mockRuleVersions: RuleVersionMeta[] = [
  {
    version: "2026.1",
    label: "2026.1 — Jan effective",
    effectiveFrom: "2026-01-01",
    status: "active",
  },
  {
    version: "2025.4",
    label: "2025.4 — Q4 retail",
    effectiveFrom: "2025-10-01",
    status: "archived",
  },
  {
    version: "2026.2-draft",
    label: "2026.2 draft (Q3)",
    effectiveFrom: "2026-07-01",
    status: "draft",
  },
];

export const mockAuditTrail: AuditTrailEntry[] = [
  {
    id: "au-1",
    entityType: "rule",
    entityLabel: "Commercial lines — core slab",
    action: "Version published",
    actor: "Policy Admin",
    at: "2026-03-18T11:00:05",
    beforeSummary: "v2025.3 · 6.8% mid-band commission",
    afterSummary: "v2026.1 · 7.2% mid-band, mult 1.0",
  },
  {
    id: "au-2",
    entityType: "payout",
    entityLabel: "Payout batch PB-2026-04-12",
    action: "Amount adjusted",
    actor: "Finance Ops",
    at: "2026-04-12T08:44:00",
    beforeSummary: "OMR 42,180 gross",
    afterSummary: "OMR 41,920 gross (clawback line 7)",
  },
  {
    id: "au-3",
    entityType: "approval",
    entityLabel: "ap-3 Marine hull override",
    action: "Stage approved",
    actor: "Finance Ops",
    at: "2026-04-07T08:30:12",
    beforeSummary: "Pending finance",
    afterSummary: "Approved · accrual posted",
  },
  {
    id: "au-4",
    entityType: "scenario",
    entityLabel: "Simulation — Base + 5% GWP",
    action: "Scenario saved",
    actor: "Sara Al-Mansoori",
    at: "2026-04-09T16:22:00",
    beforeSummary: "—",
    afterSummary: "OMR 44.1k projected vs OMR 42.2k base",
  },
  {
    id: "au-5",
    entityType: "rule",
    entityLabel: "Retail motor — retail SPIFF stack",
    action: "Slab tier edited",
    actor: "Sara Al-Mansoori",
    at: "2026-02-02T09:30:40",
    beforeSummary: "86–100% · 5.8% commission",
    afterSummary: "86–115% · 6.0% commission",
  },
];

export const mockScheduledReports: ScheduledReportJob[] = [
  {
    id: "sch-1",
    name: "Weekly payout readiness",
    format: "xlsx",
    cadence: "Every Mon 06:00",
    nextRun: "2026-04-14",
    recipients: "finance-ops@dhofar-insurance.om",
    enabled: true,
    slice: mockSliceAt(0),
  },
  {
    id: "sch-2",
    name: "Executive PDF pack",
    format: "pdf",
    cadence: "1st of month 07:00",
    nextRun: "2026-05-01",
    recipients: "cfo@dhofar-insurance.om, exco@…",
    enabled: true,
    slice: mockSliceAt(1),
  },
  {
    id: "sch-3",
    name: "Producer statements (CSV)",
    format: "csv",
    cadence: "Paused",
    nextRun: "—",
    recipients: "hr-payroll@…",
    enabled: false,
    slice: mockSliceAt(2),
  },
];

export const mockNotificationRules: NotificationAlertRule[] = [
  {
    id: "nr-1",
    name: "Payout batch released",
    trigger: "When finance posts settlement file",
    channels: ["email", "whatsapp"],
    enabled: true,
  },
  {
    id: "nr-2",
    name: "Approval SLA breach",
    trigger: "Queue item > 48h in same stage",
    channels: ["email", "sms"],
    enabled: true,
  },
  {
    id: "nr-3",
    name: "Rule engine publish",
    trigger: "New active commission version",
    channels: ["email"],
    enabled: true,
  },
];

export const mockNotificationCampaigns: NotificationCampaignDraft[] = [
  {
    id: "nc-1",
    name: "Q2 kick-off — target reminder",
    audience: "All producers · Commercial",
    channel: "email",
    status: "scheduled",
    scheduledFor: "2026-04-15T08:00:00",
  },
  {
    id: "nc-2",
    name: "SPIFF leaderboard teaser",
    audience: "Motor retail · top 200",
    channel: "sms",
    status: "draft",
  },
];

export const mockRuleEngineRules: RuleEngineRule[] = [
  {
    id: "re-1",
    name: "Motor — direct channel uplift",
    priority: 10,
    active: true,
    conditions: [
      {
        id: "c1",
        combinator: "AND",
        dimension: "product",
        mode: "include",
        values: ["Motor"],
        targetOmr: 250000,
        incentivePercent: 0.15,
      },
      {
        id: "c2",
        combinator: "AND",
        dimension: "channel",
        mode: "include",
        values: ["Direct", "Online"],
        targetOmr: 150000,
        incentivePercent: 0.25,
      },
    ],
    effectSummary: "Stacked direct channel bonus for motor lines (+0.40% total potential).",
    updatedAt: "2026-04-01T10:00:00",
    updatedBy: "Policy Admin",
  },
  {
    id: "re-2",
    name: "Exclude bancassurance from marine SPIFF",
    priority: 20,
    active: true,
    conditions: [
      {
        id: "c3",
        combinator: "AND",
        dimension: "product",
        mode: "include",
        values: ["Marine"],
        targetOmr: 400000,
        incentivePercent: 1.2,
      },
      {
        id: "c4",
        combinator: "AND",
        dimension: "channel",
        mode: "exclude",
        values: ["Bancassurance"],
        targetOmr: 10000,
        incentivePercent: 0,
      },
    ],
    effectSummary: "Suppresses marine kicker if bancassurance is involved.",
    updatedAt: "2026-03-22T14:30:00",
    updatedBy: "Actuarial",
  },
  {
    id: "re-3",
    name: "Muscat medical — key staff",
    priority: 5,
    active: false,
    conditions: [
      {
        id: "c5",
        combinator: "AND",
        dimension: "region",
        mode: "include",
        values: ["Muscat"],
        targetOmr: 500000,
        incentivePercent: 0.5,
      },
      {
        id: "c6",
        combinator: "AND",
        dimension: "staff",
        mode: "include",
        values: ["ST-001", "ST-003"],
        targetOmr: 200000,
        incentivePercent: 0.45,
      },
      {
        id: "c7",
        combinator: "AND",
        dimension: "product",
        mode: "include",
        values: ["Medical"],
        targetOmr: 100000,
        incentivePercent: 0.25,
      },
    ],
    effectSummary: "Special Muscat medical stack for high-performers (+1.20% potential).",
    updatedAt: "2026-04-08T09:00:00",
    updatedBy: "Sara Al-Mansoori",
  },
];

export const mockDataQualityIssues: DataQualityIssue[] = [
  {
    id: "dq-1",
    severity: "error",
    checkName: "Policy premium completeness",
    description:
      "12 policies missing written premium before incentive run (batch 2026-04-11).",
    source: "Core policy feed",
    detectedAt: "2026-04-11T06:00:00",
    status: "open",
    slice: mockSliceAt(0),
  },
  {
    id: "dq-2",
    severity: "warning",
    checkName: "Producer hierarchy",
    description:
      "3 deals linked to inactive RM codes — commission path ambiguous.",
    source: "HR master",
    detectedAt: "2026-04-10T11:20:00",
    status: "raised_it",
    resolutionNote: "ITSD-4482 logged · awaiting HR refresh",
    slice: mockSliceAt(1),
  },
  {
    id: "dq-3",
    severity: "info",
    checkName: "Channel mapping",
    description: "Broker code BRC-992 duplicated across two legal entities.",
    source: "Channel reference",
    detectedAt: "2026-04-09T15:00:00",
    status: "resolved",
    resolutionNote: "Merged to canonical broker parent 08-Apr",
    slice: mockSliceAt(2),
  },
];

export const mockProductCommission: ProductCommissionRow[] = [
  {
    product: "Motor",
    commissionOmr: 186400,
    pctOfTotal: 38.2,
    yoyDeltaPct: 6.4,
    slice: mockSliceAt(0),
  },
  {
    product: "Medical",
    commissionOmr: 98200,
    pctOfTotal: 20.1,
    yoyDeltaPct: 3.1,
    slice: mockSliceAt(1),
  },
  {
    product: "Marine",
    commissionOmr: 75400,
    pctOfTotal: 15.4,
    yoyDeltaPct: -1.2,
    slice: mockSliceAt(2),
  },
  {
    product: "Property",
    commissionOmr: 62100,
    pctOfTotal: 12.7,
    yoyDeltaPct: 4.8,
    slice: mockSliceAt(3),
  },
  {
    product: "Engineering",
    commissionOmr: 66400,
    pctOfTotal: 13.6,
    yoyDeltaPct: 2.0,
    slice: mockSliceAt(4),
  },
];

export const mockChannelEarnings: ChannelEarningRow[] = [
  {
    channel: "Direct",
    earningsOmr: 198200,
    policies: 8420,
    slice: mockSliceAt(0),
  },
  {
    channel: "Broker",
    earningsOmr: 174800,
    policies: 6230,
    slice: mockSliceAt(1),
  },
  {
    channel: "Bancassurance",
    earningsOmr: 72100,
    policies: 2104,
    slice: mockSliceAt(2),
  },
  {
    channel: "Online",
    earningsOmr: 46400,
    policies: 3891,
    slice: mockSliceAt(3),
  },
];

export const mockBrokerPerformance: BrokerPerformanceRow[] = [
  {
    id: "br-1",
    broker: "Oman Insurance Brokers LLC",
    channel: "Broker",
    gwpOmr: 4200000,
    commissionOmr: 168000,
    rank: 1,
    slice: mockSliceAt(1),
  },
  {
    id: "br-2",
    broker: "Gulf Risk Partners",
    channel: "Broker",
    gwpOmr: 2980000,
    commissionOmr: 119200,
    rank: 2,
    slice: mockSliceAt(1),
  },
  {
    id: "br-3",
    broker: "Muscat Financial Services",
    channel: "Bancassurance",
    gwpOmr: 1850000,
    commissionOmr: 64800,
    rank: 3,
    slice: mockSliceAt(2),
  },
  {
    id: "br-4",
    broker: "Salalah Marine Agency",
    channel: "Broker",
    gwpOmr: 1120000,
    commissionOmr: 44800,
    rank: 4,
    slice: mockSliceAt(1),
  },
];

export const mockMisReportRows: MisReportRow[] = [
  {
    id: "mis-1",
    region: "Muscat",
    branch: "Head Office",
    staff: "ST-001",
    product: "Motor",
    gwpOmr: 420000,
    targetOmr: 400000,
    achievementPct: 105,
    incentivePct: 7.8,
    incentiveEarnedOmr: 32760,
  },
  {
    id: "mis-2",
    region: "Muscat",
    branch: "Ruwi",
    staff: "ST-006",
    product: "Medical",
    gwpOmr: 198000,
    targetOmr: 220000,
    achievementPct: 90,
    incentivePct: 6.1,
    incentiveEarnedOmr: 12078,
  },
  {
    id: "mis-3",
    region: "Dhofar",
    branch: "Salalah",
    staff: "ST-002",
    product: "Marine",
    gwpOmr: 310000,
    targetOmr: 280000,
    achievementPct: 110.7,
    incentivePct: 8.2,
    incentiveEarnedOmr: 25420,
  },
  {
    id: "mis-4",
    region: "Al Batinah",
    branch: "Sohar",
    staff: "ST-005",
    product: "Property",
    gwpOmr: 142000,
    targetOmr: 180000,
    achievementPct: 78.9,
    incentivePct: 0,
    incentiveEarnedOmr: 0,
  },
  {
    id: "mis-5",
    region: "National",
    branch: "Digital",
    staff: "ST-004",
    product: "Motor",
    gwpOmr: 96500,
    targetOmr: 90000,
    achievementPct: 107.2,
    incentivePct: 7.4,
    incentiveEarnedOmr: 7141,
  },
];

export const mockMisTrend: MisTrendPoint[] = [
  { period: "Nov", gwpOmr: 980000, incentiveOmr: 62400 },
  { period: "Dec", gwpOmr: 1050000, incentiveOmr: 68100 },
  { period: "Jan", gwpOmr: 1120000, incentiveOmr: 71800 },
  { period: "Feb", gwpOmr: 1080000, incentiveOmr: 69200 },
  { period: "Mar", gwpOmr: 1210000, incentiveOmr: 76400 },
  { period: "Apr", gwpOmr: 1165000, incentiveOmr: 74100 },
];

export const mockPerformanceSignals: PerformanceSignalRow[] = [
  {
    id: "ps-1",
    metric: "Team GWP run-rate",
    value: "OMR 1.02M / mo",
    context: "vs target 1.08M · rolling 8 weeks",
    slice: mockSliceAt(0),
  },
  {
    id: "ps-2",
    metric: "Incentive accrual coverage",
    value: "97.4%",
    context: "Policies with valid producer mapping",
    slice: mockSliceAt(1),
  },
  {
    id: "ps-3",
    metric: "Quality pass rate",
    value: "94%",
    context: "Pre-payout validation batches",
    slice: mockSliceAt(2),
  },
  {
    id: "ps-4",
    metric: "Avg cycle — deal to accrual",
    value: "3.2 days",
    context: "Commercial lines · median",
    slice: mockSliceAt(3),
  },
];

export const mockIntegrationLogs: IntegrationLogEntry[] = [
  {
    id: "il-1",
    at: "2026-04-11T08:12:00",
    level: "info",
    integration: "Core policy API",
    message: "Incremental sync completed · 1,240 policies",
    slice: mockSliceAt(0),
  },
  {
    id: "il-2",
    at: "2026-04-11T07:55:00",
    level: "warn",
    integration: "Broker portal feed",
    message: "12 rows skipped — missing broker licence code",
    slice: mockSliceAt(1),
  },
  {
    id: "il-3",
    at: "2026-04-10T22:01:00",
    level: "error",
    integration: "HR master",
    message: "Auth token expired — retry scheduled",
    slice: mockSliceAt(2),
  },
  {
    id: "il-4",
    at: "2026-04-10T18:40:00",
    level: "info",
    integration: "Bancassurance SFTP",
    message: "File ACK received · batch APR10-BNK",
    slice: mockSliceAt(3),
  },
];
